# Generated by Django 2.1.3 on 2018-12-25 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GICs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('issuer', models.CharField(max_length=30, verbose_name='Deterministic')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('term', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Term of GIC')),
                ('rate', models.FloatField(verbose_name='Rate')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date and Time Modified')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gics',
            unique_together={('date', 'issuer', 'amount', 'term')},
        ),
    ]
