# Generated by Django 2.1.3 on 2018-12-29 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investmentplan', '0013_auto_20181229_1434'),
        ('gic_select', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GICPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_bool', models.BooleanField(default=False, verbose_name='Current/Default Boolean')),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('ARCHIVED', 'Archived')], max_length=9, verbose_name='Current/Archived')),
                ('date_added', models.DateTimeField(editable=False, verbose_name='Date and Time Added')),
                ('date_modified', models.DateTimeField(verbose_name='Date and Time Modified')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmentplan.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='GICSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Investment Amount')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date and Time Modified')),
                ('gic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gic_select.GICs')),
                ('gic_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gic_select.GICPlan')),
            ],
        ),
    ]
