# Generated by Django 2.1.3 on 2018-12-29 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gic_select', '0002_gicplan_gicselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='gicplan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
