# Generated by Django 2.1.3 on 2018-12-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic_select', '0003_gicplan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gics',
            name='issuer',
            field=models.CharField(max_length=30, verbose_name='Issuer'),
        ),
    ]
