# Generated by Django 2.1.3 on 2019-02-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic_select', '0004_auto_20181229_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name of Insured Instituion')),
            ],
        ),
        migrations.CreateModel(
            name='DICO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name of Insured Instituion')),
            ],
        ),
    ]
