# Generated by Django 2.1.3 on 2019-02-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic_select', '0005_cdic_dico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdic',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of Insured Instituion'),
        ),
        migrations.AlterField(
            model_name='dico',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name of Insured Instituion'),
        ),
    ]
