# Generated by Django 2.1.3 on 2019-02-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gic_select', '0006_auto_20190203_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dico',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Name of Insured Instituion'),
        ),
    ]
