version: '3'

services:
  db:
    image: postgres:10.1
    container_name: robocondo_psql
    expose:
      - "5432"
    volumes:
      - mypostgresdb:/var/lib/postgresql/data/
    networks:
      - rc_net
  redis:
    image: redis:4.0.8
    container_name: redis_rc
    networks:
      - rc_net
  rabbitmq:
    image: rabbitmq:3.7.4
    container_name: rabbitmq_rc
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rc_net
  django:
    container_name: django
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8080 --settings=robocondo.settings.base
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    networks:
      - rc_net
  worker:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker_rc
    command: python ./run_celery_auto_reload.py
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - redis
    networks:
      - rc_net
  selenium_hub:
    container_name: selenium_hub
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - rc_net
  chrome:
    container_name: chrome
    image: selenium/node-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - "5900:5900"
    networks:
      - rc_net
  firefox:
    container_name: firefox
    image: selenium/node-firefox-debug
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - "5901:5900"
    networks:
      - rc_net

networks:
  rc_net:

volumes:
  mypostgresdb:
    external: true
