# Generated by Django 2.1.3 on 2018-12-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalyieldcurve',
            name='four_year',
            field=models.FloatField(default=0, verbose_name='ZC400YR'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalyieldcurve',
            name='three_month',
            field=models.FloatField(verbose_name='ZC025YR'),
        ),
    ]
