# Generated by Django 2.1.3 on 2018-12-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyyc', '0002_auto_20181215_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointegration',
            name='any_roots',
            field=models.BooleanField(verbose_name='Any Roots'),
        ),
    ]
