# Generated by Django 2.1.3 on 2018-12-16 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyyc', '0003_auto_20181215_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOCGICs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('prime', models.FloatField(verbose_name='Business Prime Rate')),
                ('one_year', models.FloatField(verbose_name='1-Year GIC')),
                ('three_year', models.FloatField(verbose_name='3-Year GIC')),
                ('five_year', models.FloatField(verbose_name='5-Year GIC')),
            ],
        ),
        migrations.CreateModel(
            name='GICs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('issuer', models.CharField(max_length=30, verbose_name='Deterministic')),
                ('term', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Term of GIC')),
                ('rate', models.FloatField(verbose_name='Term of GIC')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gics',
            unique_together={('date', 'issuer', 'term')},
        ),
    ]
