# Generated by Django 2.1.3 on 2018-12-16 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pyyc', '0004_auto_20181216_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='bocgics',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date and Time Added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bocgics',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date and Time Modified'),
        ),
        migrations.AddField(
            model_name='gics',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date and Time Added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gics',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date and Time Modified'),
        ),
    ]
