# Generated by Django 2.1.3 on 2018-12-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyyc', '0005_auto_20181216_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='gics',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gics',
            name='rate',
            field=models.FloatField(verbose_name='Rate'),
        ),
    ]
