# Generated by Django 2.1.3 on 2018-12-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyyc', '0007_auto_20181216_1851'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gics',
            unique_together={('date', 'issuer', 'amount', 'term')},
        ),
    ]
