# Generated by Django 2.1.3 on 2018-12-16 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyyc', '0009_bocgicforecast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bocgicforecast',
            name='forecast',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pyyc.Forecast'),
        ),
    ]
