# Generated by Django 2.1.3 on 2018-12-25 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyyc', '0012_auto_20181223_2039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GICs',
        ),
    ]
