# Generated by Django 2.1.3 on 2018-12-29 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyyc', '0013_delete_gics'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raw',
            unique_together=set(),
        ),
    ]
