# Generated by Django 2.1.3 on 2018-12-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyyc', '0014_auto_20181229_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inflationrate',
            name='cpi_rate',
        ),
        migrations.AddField(
            model_name='inflationrate',
            name='inflation',
            field=models.FloatField(default=0, verbose_name='Inflation'),
            preserve_default=False,
        ),
    ]
