# Generated by Django 2.1.3 on 2019-01-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyyc', '0016_forecast_current'),
    ]

    operations = [
    ]
