# Generated by Django 2.1.3 on 2019-01-01 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyyc', '0017_auto_20190101_1724'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='CurrentForecast',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time Added')),
        #         ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date and Time Modified')),
        #         ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyyc.Forecast')),
        #     ],
        # ),
    ]
