# Generated by Django 2.1.3 on 2019-01-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyyc', '0019_auto_20190101_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='group',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Forecast Group'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Current Forecast?'),
        ),
    ]
