# Generated by Django 2.0.3 on 2018-04-07 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservefundstudy', '0004_auto_20180331_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(verbose_name='Period')),
                ('opening_balance', models.FloatField(verbose_name='Opening Balance')),
                ('contributions', models.FloatField(verbose_name='Contributions')),
                ('expenditures', models.FloatField(verbose_name='Expenditures')),
                ('interest', models.FloatField(verbose_name='Interest')),
                ('closing_balance', models.FloatField(verbose_name='Closing Balance')),
                ('bank_balance', models.FloatField(verbose_name='Bank Account Balance')),
                ('current_investments', models.FloatField(verbose_name='Current Investments')),
                ('maturities', models.FloatField(verbose_name='Maturities')),
                ('term_1', models.FloatField(verbose_name='Investment Term 1')),
                ('term_2', models.FloatField(verbose_name='Investment Term 2')),
                ('term_3', models.FloatField(verbose_name='Investment Term 3')),
                ('term_4', models.FloatField(verbose_name='Investment Term 4')),
                ('term_5', models.FloatField(verbose_name='Investment Term 5')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_bool', models.BooleanField(default=False, verbose_name='Current/Default Boolean')),
                ('status', models.CharField(choices=[('CURRENT', 'Current'), ('ARCHIVED', 'Archived')], max_length=9, verbose_name='Current/Archived')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date and Time Modified')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservefundstudy.Study')),
            ],
        ),
        migrations.AddField(
            model_name='forecast',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='investmentplan.Plan'),
        ),
    ]
