# Generated by Django 2.0.3 on 2018-04-07 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investmentplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investmentplan.Plan'),
        ),
    ]
