# Generated by Django 2.0.3 on 2018-04-08 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investmentplan', '0002_auto_20180407_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='investmentplan.Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date_added',
            field=models.DateTimeField(editable=False, verbose_name='Date and Time Added'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date_modified',
            field=models.DateTimeField(verbose_name='Date and Time Modified'),
        ),
    ]
