# Generated by Django 2.0.4 on 2018-04-21 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmentplan', '0004_auto_20180408_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='month',
            field=models.DateTimeField(default=datetime.datetime(1000, 1, 1, 0, 0), verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='total_purchases',
            field=models.FloatField(default=0, verbose_name='Total Purchases'),
        ),
    ]
