# Generated by Django 2.0.4 on 2018-04-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investmentplan', '0005_auto_20180421_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='month',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='total_purchases',
        ),
    ]
