# Generated by Django 2.0.4 on 2018-04-21 21:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investmentplan', '0006_auto_20180421_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='month',
            field=models.DateTimeField(default=datetime.datetime(1000, 1, 1, 0, 0), verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='total_purchases',
            field=models.FloatField(default=0, verbose_name='Total Purchases'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investmentplan.Plan'),
        ),
    ]
