# Generated by Django 2.0.4 on 2018-04-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmentplan', '0007_auto_20180421_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='month',
            field=models.DateTimeField(verbose_name='Month'),
        ),
    ]
