# Generated by Django 2.0.4 on 2018-04-24 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmentplan', '0008_auto_20180424_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='month',
            field=models.DateTimeField(default=datetime.datetime(1000, 1, 1, 0, 0), verbose_name='Month'),
        ),
    ]
