# Generated by Django 2.0.4 on 2018-04-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investmentplan', '0009_auto_20180424_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='month',
        ),
    ]
