# Generated by Django 2.0.4 on 2018-04-24 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmentplan', '0010_remove_forecast_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecast',
            name='total_purchases',
        ),
        migrations.AddField(
            model_name='forecast',
            name='month',
            field=models.DateTimeField(default=datetime.datetime(1000, 1, 1, 0, 0), verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='total_investments',
            field=models.FloatField(default=0, verbose_name='Total Investments'),
        ),
    ]
