# Generated by Django 2.0.5 on 2018-05-14 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('investmentplan', '0011_auto_20180424_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='month',
            field=models.DateTimeField(default=datetime.datetime(1000, 1, 1, 0, 0, tzinfo=utc), verbose_name='Month'),
        ),
    ]
