# Generated by Django 2.1.3 on 2018-12-29 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('investmentplan', '0012_auto_20180514_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='month',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc), verbose_name='Month'),
        ),
    ]
