# Generated by Django 2.1.3 on 2018-12-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investmentplan', '0013_auto_20181229_1434'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together={('plan', 'period', 'month')},
        ),
    ]
