# Generated by Django 2.1.3 on 2019-02-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investmentplan', '0014_auto_20181229_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='time',
            field=models.FloatField(default=0, verbose_name='Time to Complete'),
        ),
    ]
