# Generated by Django 2.1.3 on 2019-03-04 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('condo', '0018_auto_20190218_2028'),
        ('reservefundstudy', '0011_auto_20190207_1558'),
        ('pyyc', '0020_auto_20190109_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condo.Condo')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.PositiveSmallIntegerField(verbose_name='Forecast Group')),
                ('period', models.IntegerField(verbose_name='Period')),
                ('month', models.DateTimeField(verbose_name='Month')),
                ('opening_balance', models.FloatField(verbose_name='Opening Balance')),
                ('contributions', models.FloatField(verbose_name='Contributions')),
                ('expenditures', models.FloatField(verbose_name='Expenditures')),
                ('interest', models.FloatField(verbose_name='Interest')),
                ('closing_balance', models.FloatField(verbose_name='Closing Balance')),
                ('bank_balance', models.FloatField(verbose_name='Bank Account Balance')),
                ('current_investments', models.FloatField(verbose_name='Current Investments')),
                ('maturities', models.FloatField(verbose_name='Maturities')),
                ('term_1', models.FloatField(verbose_name='Investment Term 1')),
                ('term_2', models.FloatField(verbose_name='Investment Term 2')),
                ('term_3', models.FloatField(verbose_name='Investment Term 3')),
                ('term_4', models.FloatField(verbose_name='Investment Term 4')),
                ('term_5', models.FloatField(verbose_name='Investment Term 5')),
                ('total_investments', models.FloatField(default=0, verbose_name='Total Investments')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='forecast',
            unique_together={('group', 'period', 'month')},
        ),
        migrations.AddField(
            model_name='analysis',
            name='forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyyc.Forecast'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservefundstudy.Study'),
        ),
    ]
