# Generated by Django 2.0.2 on 2018-03-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Condo Name')),
            ],
        ),
        migrations.CreateModel(
            name='Contributions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont_year_1', models.FloatField(verbose_name='Year 1')),
                ('cont_year_2', models.FloatField(verbose_name='Year 2')),
                ('cont_year_3', models.FloatField(verbose_name='Year 3')),
                ('cont_year_4', models.FloatField(verbose_name='Year 4')),
                ('cont_year_5', models.FloatField(verbose_name='Year 5')),
                ('cont_year_6', models.FloatField(verbose_name='Year 6')),
                ('cont_year_7', models.FloatField(verbose_name='Year 7')),
                ('cont_year_8', models.FloatField(verbose_name='Year 8')),
                ('cont_year_9', models.FloatField(verbose_name='Year 9')),
                ('cont_year_10', models.FloatField(verbose_name='Year 10')),
                ('cont_year_11', models.FloatField(verbose_name='Year 11')),
                ('cont_year_12', models.FloatField(verbose_name='Year 12')),
                ('cont_year_13', models.FloatField(verbose_name='Year 13')),
                ('cont_year_14', models.FloatField(verbose_name='Year 14')),
                ('cont_year_15', models.FloatField(verbose_name='Year 15')),
                ('cont_year_16', models.FloatField(verbose_name='Year 16')),
                ('cont_year_17', models.FloatField(verbose_name='Year 17')),
                ('cont_year_18', models.FloatField(verbose_name='Year 18')),
                ('cont_year_19', models.FloatField(verbose_name='Year 19')),
                ('cont_year_20', models.FloatField(verbose_name='Year 20')),
                ('cont_year_21', models.FloatField(verbose_name='Year 21')),
                ('cont_year_22', models.FloatField(verbose_name='Year 22')),
                ('cont_year_23', models.FloatField(verbose_name='Year 23')),
                ('cont_year_24', models.FloatField(verbose_name='Year 24')),
                ('cont_year_25', models.FloatField(verbose_name='Year 25')),
                ('cont_year_26', models.FloatField(verbose_name='Year 26')),
                ('cont_year_27', models.FloatField(verbose_name='Year 27')),
                ('cont_year_28', models.FloatField(verbose_name='Year 28')),
                ('cont_year_29', models.FloatField(verbose_name='Year 29')),
                ('cont_year_30', models.FloatField(null=True, verbose_name='Year 30')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_year_1', models.FloatField(verbose_name='Year 1')),
                ('exp_year_2', models.FloatField(verbose_name='Year 2')),
                ('exp_year_3', models.FloatField(verbose_name='Year 3')),
                ('exp_year_4', models.FloatField(verbose_name='Year 4')),
                ('exp_year_5', models.FloatField(verbose_name='Year 5')),
                ('exp_year_6', models.FloatField(verbose_name='Year 6')),
                ('exp_year_7', models.FloatField(verbose_name='Year 7')),
                ('exp_year_8', models.FloatField(verbose_name='Year 8')),
                ('exp_year_9', models.FloatField(verbose_name='Year 9')),
                ('exp_year_10', models.FloatField(verbose_name='Year 10')),
                ('exp_year_11', models.FloatField(verbose_name='Year 11')),
                ('exp_year_12', models.FloatField(verbose_name='Year 12')),
                ('exp_year_13', models.FloatField(verbose_name='Year 13')),
                ('exp_year_14', models.FloatField(verbose_name='Year 14')),
                ('exp_year_15', models.FloatField(verbose_name='Year 15')),
                ('exp_year_16', models.FloatField(verbose_name='Year 16')),
                ('exp_year_17', models.FloatField(verbose_name='Year 17')),
                ('exp_year_18', models.FloatField(verbose_name='Year 18')),
                ('exp_year_19', models.FloatField(verbose_name='Year 19')),
                ('exp_year_20', models.FloatField(verbose_name='Year 20')),
                ('exp_year_21', models.FloatField(verbose_name='Year 21')),
                ('exp_year_22', models.FloatField(verbose_name='Year 22')),
                ('exp_year_23', models.FloatField(verbose_name='Year 23')),
                ('exp_year_24', models.FloatField(verbose_name='Year 24')),
                ('exp_year_25', models.FloatField(verbose_name='Year 25')),
                ('exp_year_26', models.FloatField(verbose_name='Year 26')),
                ('exp_year_27', models.FloatField(verbose_name='Year 27')),
                ('exp_year_28', models.FloatField(verbose_name='Year 28')),
                ('exp_year_29', models.FloatField(verbose_name='Year 29')),
                ('exp_year_30', models.FloatField(null=True, verbose_name='Year 30')),
            ],
        ),
        migrations.CreateModel(
            name='ReserveFundStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Reserve Fund Study')),
                ('first_year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045), (2046, 2046), (2047, 2047), (2048, 2048)], default=2018, verbose_name='First Year of Study')),
                ('last_year', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045), (2046, 2046), (2047, 2047), (2048, 2048)], default=2048, verbose_name='Last Year of Study')),
                ('years', models.IntegerField(default=0, verbose_name='Number of Years in Study')),
                ('opening_balance', models.FloatField(default=0, verbose_name='Opening Balance')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='Date Modified')),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='condo.Condo')),
            ],
        ),
        migrations.AddField(
            model_name='expenditures',
            name='study',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='condo.ReserveFundStudy'),
        ),
        migrations.AddField(
            model_name='contributions',
            name='study',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='condo.ReserveFundStudy'),
        ),
    ]
