# Generated by Django 2.0.2 on 2018-03-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributions',
            name='study',
        ),
        migrations.RemoveField(
            model_name='expenditures',
            name='study',
        ),
        migrations.RemoveField(
            model_name='reservefundstudy',
            name='condo',
        ),
        migrations.DeleteModel(
            name='Contributions',
        ),
        migrations.DeleteModel(
            name='Expenditures',
        ),
        migrations.DeleteModel(
            name='ReserveFundStudy',
        ),
    ]
