# Generated by Django 2.0.3 on 2018-03-31 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0002_auto_20180303_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='condo',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='condo',
            name='date_modified',
            field=models.DateField(auto_now=True, verbose_name='Date Modified'),
        ),
    ]
