# Generated by Django 2.0.3 on 2018-03-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0003_auto_20180331_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condo',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and Time Added'),
        ),
        migrations.AlterField(
            model_name='condo',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date and Time Modified'),
        ),
    ]
