# Generated by Django 2.0.5 on 2018-05-14 18:42

from django.db import migrations, models
import django.db.models.deletion
import robocondo.global_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0004_auto_20180331_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(verbose_name='Reserve Balance')),
                ('date', models.DateTimeField(editable=False, verbose_name='Date')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time Added')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='Account Number')),
                ('institution', models.CharField(max_length=100, verbose_name='Financial Institution')),
                ('type', models.CharField(choices=[('OPERATING', 'Operating Account'), ('RESERVE', 'Reserve Account')], max_length=20, verbose_name='Account Type')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date and Time Modified')),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condo.Condo')),
            ],
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_number', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Instrument Number')),
                ('institution', models.CharField(max_length=100, verbose_name='Financial Institution')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('interest_rate', models.CharField(max_length=10, validators=[robocondo.global_helpers.valid_pct], verbose_name='Interest Rate')),
                ('maturity_date', models.DateField(verbose_name='Maturity Date')),
                ('interest_frequency', models.CharField(choices=[('ANNUAL', 'Annual'), ('SEMI_ANNUAL', 'Semi-Annual'), ('QUARTERLY', 'Quarterly'), ('MATURITY', 'Maturity')], max_length=20, verbose_name='Interest Frequency')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date and Time Modified')),
            ],
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condo.BankAccounts'),
        ),
    ]
