# Generated by Django 2.0.5 on 2018-05-14 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0005_auto_20180514_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='condo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='condo.Condo'),
            preserve_default=False,
        ),
    ]
