# Generated by Django 2.0.5 on 2018-05-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0006_investments_condo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='type',
            field=models.CharField(choices=[('OPERATING', 'Operating'), ('RESERVE', 'Reserve')], max_length=20, verbose_name='Account Type'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccounts',
            unique_together={('condo', 'type')},
        ),
    ]
