# Generated by Django 2.0.5 on 2018-05-14 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0007_auto_20180514_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='balance',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reserve Balance'),
        ),
    ]
