# Generated by Django 2.0.5 on 2018-05-14 23:45

import django.core.validators
from django.db import migrations, models
import robocondo.global_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0008_auto_20180514_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='interest_rate',
            field=models.FloatField(max_length=10, validators=[robocondo.global_helpers.valid_pct], verbose_name='Interest Rate'),
        ),
    ]
