# Generated by Django 2.0.5 on 2018-05-16 02:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0009_auto_20180514_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='interest_rate',
            field=models.FloatField(max_length=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Interest Rate'),
        ),
    ]
