# Generated by Django 2.0.5 on 2018-05-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0010_auto_20180516_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='maturity_date',
            field=models.DateTimeField(verbose_name='Maturity Date'),
        ),
    ]
