# Generated by Django 2.1.3 on 2018-12-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0011_auto_20180521_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccounts',
            name='spread',
            field=models.FloatField(default=0.03, verbose_name='Spread Below Prime Rate'),
            preserve_default=False,
        ),
    ]
