# Generated by Django 2.1.3 on 2019-02-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0012_bankaccounts_spread'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
