# Generated by Django 2.1.3 on 2019-02-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0013_investments_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='institution',
            field=models.CharField(max_length=400, verbose_name='Financial Institution'),
        ),
        migrations.AlterField(
            model_name='condo',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='Condo Name'),
        ),
    ]
