# Generated by Django 2.1.3 on 2019-02-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0014_auto_20190203_2340'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccounts',
            unique_together=set(),
        ),
    ]
