# Generated by Django 2.1.3 on 2019-02-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0015_auto_20190207_0454'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccounts',
            unique_together={('account_number', 'institution')},
        ),
    ]
