# Generated by Django 2.1.3 on 2019-02-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0016_auto_20190207_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccounts',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
