# Generated by Django 2.1.3 on 2019-02-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0017_bankaccounts_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condo',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Condo Name'),
        ),
    ]
