# Generated by Django 2.0.2 on 2018-03-03 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0002_auto_20180303_2041'),
        ('reservefundstudy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReserveFundStudy',
            new_name='Study',
        ),
    ]
