# Generated by Django 2.0.3 on 2018-03-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservefundstudy', '0002_auto_20180303_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date and Time Added'),
        ),
        migrations.AlterField(
            model_name='study',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date and Time Modified'),
        ),
    ]
