# Generated by Django 2.0.3 on 2018-03-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservefundstudy', '0003_auto_20180331_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_1',
            field=models.FloatField(null=True, verbose_name='Year 1'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_10',
            field=models.FloatField(null=True, verbose_name='Year 10'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_11',
            field=models.FloatField(null=True, verbose_name='Year 11'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_12',
            field=models.FloatField(null=True, verbose_name='Year 12'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_13',
            field=models.FloatField(null=True, verbose_name='Year 13'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_14',
            field=models.FloatField(null=True, verbose_name='Year 14'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_15',
            field=models.FloatField(null=True, verbose_name='Year 15'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_16',
            field=models.FloatField(null=True, verbose_name='Year 16'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_17',
            field=models.FloatField(null=True, verbose_name='Year 17'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_18',
            field=models.FloatField(null=True, verbose_name='Year 18'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_19',
            field=models.FloatField(null=True, verbose_name='Year 19'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_2',
            field=models.FloatField(null=True, verbose_name='Year 2'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_20',
            field=models.FloatField(null=True, verbose_name='Year 20'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_21',
            field=models.FloatField(null=True, verbose_name='Year 21'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_22',
            field=models.FloatField(null=True, verbose_name='Year 22'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_23',
            field=models.FloatField(null=True, verbose_name='Year 23'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_24',
            field=models.FloatField(null=True, verbose_name='Year 24'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_25',
            field=models.FloatField(null=True, verbose_name='Year 25'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_26',
            field=models.FloatField(null=True, verbose_name='Year 26'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_27',
            field=models.FloatField(null=True, verbose_name='Year 27'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_28',
            field=models.FloatField(null=True, verbose_name='Year 28'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_29',
            field=models.FloatField(null=True, verbose_name='Year 29'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_3',
            field=models.FloatField(null=True, verbose_name='Year 3'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_4',
            field=models.FloatField(null=True, verbose_name='Year 4'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_5',
            field=models.FloatField(null=True, verbose_name='Year 5'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_6',
            field=models.FloatField(null=True, verbose_name='Year 6'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_7',
            field=models.FloatField(null=True, verbose_name='Year 7'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_8',
            field=models.FloatField(null=True, verbose_name='Year 8'),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_9',
            field=models.FloatField(null=True, verbose_name='Year 9'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_1',
            field=models.FloatField(null=True, verbose_name='Year 1'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_10',
            field=models.FloatField(null=True, verbose_name='Year 10'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_11',
            field=models.FloatField(null=True, verbose_name='Year 11'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_12',
            field=models.FloatField(null=True, verbose_name='Year 12'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_13',
            field=models.FloatField(null=True, verbose_name='Year 13'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_14',
            field=models.FloatField(null=True, verbose_name='Year 14'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_15',
            field=models.FloatField(null=True, verbose_name='Year 15'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_16',
            field=models.FloatField(null=True, verbose_name='Year 16'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_17',
            field=models.FloatField(null=True, verbose_name='Year 17'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_18',
            field=models.FloatField(null=True, verbose_name='Year 18'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_19',
            field=models.FloatField(null=True, verbose_name='Year 19'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_2',
            field=models.FloatField(null=True, verbose_name='Year 2'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_20',
            field=models.FloatField(null=True, verbose_name='Year 20'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_21',
            field=models.FloatField(null=True, verbose_name='Year 21'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_22',
            field=models.FloatField(null=True, verbose_name='Year 22'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_23',
            field=models.FloatField(null=True, verbose_name='Year 23'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_24',
            field=models.FloatField(null=True, verbose_name='Year 24'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_25',
            field=models.FloatField(null=True, verbose_name='Year 25'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_26',
            field=models.FloatField(null=True, verbose_name='Year 26'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_27',
            field=models.FloatField(null=True, verbose_name='Year 27'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_28',
            field=models.FloatField(null=True, verbose_name='Year 28'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_29',
            field=models.FloatField(null=True, verbose_name='Year 29'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_3',
            field=models.FloatField(null=True, verbose_name='Year 3'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_4',
            field=models.FloatField(null=True, verbose_name='Year 4'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_5',
            field=models.FloatField(null=True, verbose_name='Year 5'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_6',
            field=models.FloatField(null=True, verbose_name='Year 6'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_7',
            field=models.FloatField(null=True, verbose_name='Year 7'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_8',
            field=models.FloatField(null=True, verbose_name='Year 8'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_9',
            field=models.FloatField(null=True, verbose_name='Year 9'),
        ),
    ]
