# Generated by Django 2.0.5 on 2018-05-14 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condo', '0007_auto_20180514_2313'),
        ('reservefundstudy', '0004_auto_20180331_1645'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='study',
            unique_together={('condo', 'date')},
        ),
    ]
