# Generated by Django 2.0.5 on 2018-05-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservefundstudy', '0005_auto_20180514_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributions',
            name='study',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservefundstudy.Study'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='study',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservefundstudy.Study'),
        ),
        migrations.AlterField(
            model_name='study',
            name='condo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condo.Condo'),
        ),
    ]
