# Generated by Django 2.1.3 on 2019-01-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservefundstudy', '008_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Current Forecast Used for Projections?'),
        ),
    ]
