# Generated by Django 2.1.3 on 2019-02-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservefundstudy', '0009_study_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='study',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Current'),
        ),
    ]
