# Generated by Django 2.1.3 on 2019-02-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservefundstudy', '0010_auto_20190203_1336'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='study',
            unique_together=set(),
        ),
    ]
