# Generated by Django 2.1.3 on 2019-01-01 16:22

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('reservefundstudy', '0007_auto_20190101_0204')
    ]

    operations = []
