# Generated by Django 2.0.2 on 2018-02-24 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_1', models.FloatField(verbose_name='Year 1')),
                ('year_2', models.FloatField(verbose_name='Year 2')),
                ('year_3', models.FloatField(verbose_name='Year 3')),
                ('year_4', models.FloatField(verbose_name='Year 4')),
                ('year_5', models.FloatField(verbose_name='Year 5')),
                ('year_6', models.FloatField(verbose_name='Year 6')),
                ('year_7', models.FloatField(verbose_name='Year 7')),
                ('year_8', models.FloatField(verbose_name='Year 8')),
                ('year_9', models.FloatField(verbose_name='Year 9')),
                ('year_10', models.FloatField(verbose_name='Year 10')),
                ('year_11', models.FloatField(verbose_name='Year 11')),
                ('year_12', models.FloatField(verbose_name='Year 12')),
                ('year_13', models.FloatField(verbose_name='Year 13')),
                ('year_14', models.FloatField(verbose_name='Year 14')),
                ('year_15', models.FloatField(verbose_name='Year 15')),
                ('year_16', models.FloatField(verbose_name='Year 16')),
                ('year_17', models.FloatField(verbose_name='Year 17')),
                ('year_18', models.FloatField(verbose_name='Year 18')),
                ('year_19', models.FloatField(verbose_name='Year 19')),
                ('year_20', models.FloatField(verbose_name='Year 20')),
                ('year_21', models.FloatField(verbose_name='Year 21')),
                ('year_22', models.FloatField(verbose_name='Year 22')),
                ('year_23', models.FloatField(verbose_name='Year 23')),
                ('year_24', models.FloatField(verbose_name='Year 24')),
                ('year_25', models.FloatField(verbose_name='Year 25')),
                ('year_26', models.FloatField(verbose_name='Year 26')),
                ('year_27', models.FloatField(verbose_name='Year 27')),
                ('year_28', models.FloatField(verbose_name='Year 28')),
                ('year_29', models.FloatField(verbose_name='Year 29')),
                ('year_30', models.FloatField(verbose_name='Year 30')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_1', models.FloatField(verbose_name='Year 1')),
                ('year_2', models.FloatField(verbose_name='Year 2')),
                ('year_3', models.FloatField(verbose_name='Year 3')),
                ('year_4', models.FloatField(verbose_name='Year 4')),
                ('year_5', models.FloatField(verbose_name='Year 5')),
                ('year_6', models.FloatField(verbose_name='Year 6')),
                ('year_7', models.FloatField(verbose_name='Year 7')),
                ('year_8', models.FloatField(verbose_name='Year 8')),
                ('year_9', models.FloatField(verbose_name='Year 9')),
                ('year_10', models.FloatField(verbose_name='Year 10')),
                ('year_11', models.FloatField(verbose_name='Year 11')),
                ('year_12', models.FloatField(verbose_name='Year 12')),
                ('year_13', models.FloatField(verbose_name='Year 13')),
                ('year_14', models.FloatField(verbose_name='Year 14')),
                ('year_15', models.FloatField(verbose_name='Year 15')),
                ('year_16', models.FloatField(verbose_name='Year 16')),
                ('year_17', models.FloatField(verbose_name='Year 17')),
                ('year_18', models.FloatField(verbose_name='Year 18')),
                ('year_19', models.FloatField(verbose_name='Year 19')),
                ('year_20', models.FloatField(verbose_name='Year 20')),
                ('year_21', models.FloatField(verbose_name='Year 21')),
                ('year_22', models.FloatField(verbose_name='Year 22')),
                ('year_23', models.FloatField(verbose_name='Year 23')),
                ('year_24', models.FloatField(verbose_name='Year 24')),
                ('year_25', models.FloatField(verbose_name='Year 25')),
                ('year_26', models.FloatField(verbose_name='Year 26')),
                ('year_27', models.FloatField(verbose_name='Year 27')),
                ('year_28', models.FloatField(verbose_name='Year 28')),
                ('year_29', models.FloatField(verbose_name='Year 29')),
                ('year_30', models.FloatField(verbose_name='Year 30')),
            ],
        ),
        migrations.CreateModel(
            name='ReserveStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of Reserve Fund Study')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Date Added')),
                ('date_modified', models.DateField(auto_now=True, verbose_name='Date Modified')),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accountmanager.Condo')),
            ],
        ),
        migrations.AddField(
            model_name='expenditures',
            name='reserve_study',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accountmanager.ReserveStudy'),
        ),
        migrations.AddField(
            model_name='contributions',
            name='reserve_study',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accountmanager.ReserveStudy'),
        ),
    ]
