# Generated by Django 2.0.2 on 2018-02-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanager', '0002_auto_20180224_0634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReserveStudy',
            new_name='ReserveFundStudy',
        ),
    ]
