# Generated by Django 2.0.2 on 2018-02-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanager', '0003_auto_20180224_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributions',
            old_name='reserve_study',
            new_name='study',
        ),
        migrations.RenameField(
            model_name='expenditures',
            old_name='reserve_study',
            new_name='study',
        ),
        migrations.AddField(
            model_name='reservefundstudy',
            name='first_year',
            field=models.IntegerField(default=0, max_length=4, verbose_name='First Year of Study'),
        ),
        migrations.AddField(
            model_name='reservefundstudy',
            name='last_year',
            field=models.IntegerField(default=0, max_length=4, verbose_name='Last Year of Study'),
        ),
        migrations.AddField(
            model_name='reservefundstudy',
            name='opening_balanace',
            field=models.FloatField(default=0, verbose_name='Opening Balance'),
        ),
    ]
