# Generated by Django 2.0.2 on 2018-02-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanager', '0004_auto_20180224_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservefundstudy',
            old_name='opening_balanace',
            new_name='opening_balance',
        ),
        migrations.AddField(
            model_name='reservefundstudy',
            name='years',
            field=models.IntegerField(default=0, verbose_name='Number of Years in Study'),
        ),
        migrations.AlterField(
            model_name='reservefundstudy',
            name='first_year',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045), (2046, 2046), (2047, 2047), (2048, 2048)], default=2018, verbose_name='First Year of Study'),
        ),
        migrations.AlterField(
            model_name='reservefundstudy',
            name='last_year',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040), (2041, 2041), (2042, 2042), (2043, 2043), (2044, 2044), (2045, 2045), (2046, 2046), (2047, 2047), (2048, 2048)], default=2048, verbose_name='Last Year of Study'),
        ),
    ]
