# Generated by Django 2.0.2 on 2018-02-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanager', '0006_auto_20180227_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributions',
            name='cont_year_30',
            field=models.FloatField(null=True, verbose_name='Year 30'),
        ),
        migrations.AlterField(
            model_name='expenditures',
            name='exp_year_30',
            field=models.FloatField(null=True, verbose_name='Year 30'),
        ),
    ]
