# Generated by Django 2.0.2 on 2018-03-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountmanager', '0007_auto_20180228_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributions',
            name='study',
        ),
        migrations.RemoveField(
            model_name='expenditures',
            name='study',
        ),
        migrations.RemoveField(
            model_name='reservefundstudy',
            name='condo',
        ),
        migrations.DeleteModel(
            name='Condo',
        ),
        migrations.DeleteModel(
            name='Contributions',
        ),
        migrations.DeleteModel(
            name='Expenditures',
        ),
        migrations.DeleteModel(
            name='ReserveFundStudy',
        ),
    ]
